pacientes/urls.py
from django.urls import path, include
from pacientes.views import *

urlpatterns = [

    path("pacientes/", pacientes, name="pacientes"),
    path("filtros/", filtros, name="filtros"),
    path("pacientes/registrar/", registrar_paciente, name="paciente_registrar"),
    path("pacientes/registrar-inf/", registrar_paciente_inf, name="paciente_registrar_inf"),
    path("pacientes/detalhes/<int:pk>/", paciente_detalhes, name="paciente_detalhes"),
    path("pacientes/detalhes-inf/<int:pk>/", paciente_detalhes_inf, name="paciente_detalhes_inf"),
    path("pacientes/editar/<int:pk>/", PacienteUpdate.as_view(), name="paciente_editar"),
    path("pacientes/editar-inf/<int:pk>/", PacienteInfantilUpdate.as_view(), name="paciente_editar_inf"),
    path("paciente/delete/<int:pk>/", PacienteDelete.as_view(), name="paciente_delete"),
    path("paciente/delete-inf/<int:pk>/", PacienteInfantilDelete.as_view(), name="paciente_delete_inf"),
    path("agenda/", agenda, name="agenda"),
    path("", inicio, name="inicio"),
    path("opcoes/", opcoes, name="opcoes"),

    path("pacientes-menu/", registrar_paciente_2, name="pacientes_menu"),
]
####

soft_clinica/urls.py
from django.contrib import admin
from django.urls import path, include
from .api import api
from pacientes.views import Teste2ViewSet, TesteViewSet
from rest_framework import routers
from django.conf.urls.static import static
from django.conf import settings

router = routers.DefaultRouter()
router.register(r'teste2', Teste2ViewSet)
router.register(r'teste', TesteViewSet)
urlpatterns = [
    path("api-rest/", include(router.urls)),
    path('api/v1/', api.urls),
    path('admin/', admin.site.urls),
    path('', include("pacientes.urls")),
    path('', include("usuarios.urls")),
    path('', include("distribuicao.urls")),
    path('', include("prontuario.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usuarios/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from usuarios.views import signup_view, cadastro_funcionario, cadastro_docente, cadastro_discente

urlpatterns = [
    path("login/", auth_views.LoginView.as_view(
        template_name="usuarios/login.html"
    ), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path('signup/', signup_view, name="signup"),

    path('cadastro-funcionario/', cadastro_funcionario, name="cadastro_funcionario"),
    path('cadastro-docente/', cadastro_docente, name="cadastro_docente"),
    path('cadastro-discente/', cadastro_discente, name="cadastro_discente"),




]

pacientes/models.py
from django.db import models
from django.urls import reverse

SEXO_BIOLOGICO = [
    ("MASCULINO", "masculino"),
    ("FEMININO", "feminino"),
]

RACA = [
    ("BRANCO", "branco"),
    ("PARDO", "pardo"),
    ("PRETO", "preto"),
    ("INDIGENA", "indigena"),
    ("AMARELO", "amarelo"),
]

ESTADO_CIVIL = [
    ("SOLTEIRO", "Solteiro"),
    ("CASADO", "Casado"),
    ("SEPARADO", "Separado"),
    ("DIVORCIADO", "Divorciado"),
    ("VIUVO", "Viúvo"),
]
A_F = [
    ("S", "Sim"),
    ("N", "Não"),
]

GRAU_INSTRUCAO = [
    ('NIVEL 1', (
        ('ANALFABETO', 'Analfabeto'),
        ('5º_ANO_INCOMPLETO', 'Até 5º Ano Incompleto'),
        ('5º_ANO_COMPLETO', 'Até 5º Ano completo'),
        ('6º_AO_9º_Ano_do_Fundamental', '6º ao 9º Ano do Fundamental'),
    )
     ),
    ('NIVEL 2', (
        ('Fundamental_Completo', 'Fundamental Completo'),
        ('Médio Incompleto', 'Médio Incompleto'),
    )
     ),
    ('NIVEL 3', (
        ('Médio Completo', 'Médio Completo'),
        ('Superior Incompleto', 'Superior Incompleto'),
    )
     ),
    ('NIVEL 4', (
        ('Superior Completo', 'Superior Completo'),
    )
     ),
    ('NIVEL 5', (
        ('Mestrado', 'Mestrado'),
        ('Doutorado', 'Doutorado'),
    )
     ),
]

UF_CHOICES = (
    ('AC', 'Acre'),
    ('AM', 'Amazonas'),
    ('AL', 'Alagoas'),
    ('AP', 'Amapá'),
    ('BA', 'Bahia'),
    ('CE', 'Ceará'),
    ('DF', 'Distrito Federal'),
    ('ES', 'Espírito Santo'),
    ('GO', 'Goiás'),
    ('MA', 'Maranhão'),
    ('MG', 'Minas Gerais'),
    ('MS', 'Mato Grosso do Sul'),
    ('MT', 'Mato Grosso'),
    ('PA', 'Pará'),
    ('PB', 'Paraíba'),
    ('PE', 'Pernambuco'),
    ('PI', 'Piauí'),
    ('PR', 'Paraná'),
    ('RJ', 'Rio de Janeiro'),
    ('RN', 'Rio Grande do Norte'),
    ('RO', 'Rondônia'),
    ('RR', 'Roraima'),
    ('RS', 'Rio Grande do Sul'),
    ('SC', 'Santa Catarina'),
    ('SE', 'Sergipe'),
    ('SP', 'São Paulo'),
    ('TO', 'Tocantins')
)


class Paciente(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)
    id = models.IntegerField(primary_key=True)
    prontuario = models.CharField("prontuario", max_length=200, blank=True)
    nome = models.CharField(verbose_name="Nome", max_length=200)
    nome_social = models.CharField(verbose_name="Nome Social", max_length=200, blank=True)
    data_nascimento = models.DateField(verbose_name="Data de Nascimento", auto_now=False, auto_now_add=False,
                                       blank=True)
    sexo_biologico = models.CharField(verbose_name="Sexo Biologico", max_length=200, blank=True)
    rg = models.CharField(verbose_name="RG", max_length=200, blank=True)
    cpf = models.CharField(verbose_name="CPF", max_length=200, blank=True)
    raca = models.CharField(verbose_name="Raça", max_length=200, blank=True)
    estado_civil = models.CharField(verbose_name="Estado Civil", max_length=200, blank=True)
    grau_instrucao = models.CharField(verbose_name="Grau de Instrução", max_length=200, blank=True)
    endereco = models.CharField(verbose_name="Endereço", max_length=200, blank=True)
    cep = models.CharField(verbose_name="CEP", max_length=200, blank=True)
    bairro = models.CharField(verbose_name="Bairro", max_length=200, blank=True)
    cidade = models.CharField(verbose_name="Cidade", max_length=200, blank=True)
    uf = models.CharField(verbose_name="UF", max_length=2, blank=True)
    telefone_celular = models.CharField(verbose_name="Telefone Celular", max_length=200, blank=True)
    informacoes_complementares = models.TextField(verbose_name="Informações Complementares", blank=True)

    def __str__(self):
        return self.nome

    def get_absolute_url(self):
        return reverse("paciente_detalhes", kwargs={"pk": self.pk})


class PacienteInfantil(models.Model):
    responsavel = models.CharField(verbose_name="Reponsavel", max_length=200)
    nome = models.CharField(verbose_name="Nome", max_length=200)
    nome_social = models.CharField(verbose_name="Nome Social", max_length=200, blank=True)
    data_nascimento = models.DateField(verbose_name="Data de Nascimento", auto_now=False, auto_now_add=False)
    sexo_biologico = models.CharField(verbose_name="Sexo Biologico", max_length=200)
    rg = models.CharField(verbose_name="RG", max_length=200, blank=True)
    cpf = models.CharField(verbose_name="CPF", max_length=200)
    raca = models.CharField(verbose_name="Raça", max_length=200)
    estado_civil = models.CharField(verbose_name="Estado Civil", max_length=200)
    grau_instrucao = models.CharField(verbose_name="Grau de Instrução", max_length=200)
    endereco = models.CharField(verbose_name="Endereço", max_length=200)
    cep = models.CharField(verbose_name="CEP", max_length=200)
    bairro = models.CharField(verbose_name="Bairro", max_length=200)
    cidade = models.CharField(verbose_name="Cidade", max_length=200)
    uf = models.CharField(verbose_name="UF", max_length=200)
    telefone_celular = models.CharField(verbose_name="Telefone Celular", max_length=200)
    informacoes_complementares = models.TextField(verbose_name="Informações Complementares")

    def __str__(self):
        return self.nome

    class Meta:
        verbose_name = "Paciente Infantil"
        verbose_name_plural = "Pacientes Infantis"


class Teste(models.Model):
    testando = models.CharField(max_length=255, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.testando}"

    class Meta:
        verbose_name_plural = "Testes"


class Teste2(models.Model):
    testando = models.CharField(max_length=255, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.testando}"

    class Meta:
        verbose_name_plural = "Teste2s"

usuarios/models.py
from django.db import models
from django.contrib.auth.models import User


class Funcionario(models.Model):
    usuario = models.OneToOneField(User, on_delete=models.CASCADE, related_name="funcionario")
    imagem = models.ImageField(null=True, blank=True, default='padrao.png')
    #image = models.
    matricula = models.CharField(verbose_name="MatFunc", max_length=200, default="nenhuma")
    nome = models.CharField(verbose_name="Nome", max_length=200)
    telefone = models.CharField(verbose_name="Telefone", max_length=15)
    email = models.EmailField(verbose_name="Email", max_length=200)

    def __str__(self):
        return self.nome


class Docente(models.Model):
    usuario = models.OneToOneField(User, on_delete=models.CASCADE, related_name="docente")
    imagem = models.ImageField(null=True, blank=True, default='padrao.png')
    matricula = models.CharField(verbose_name="MatDocente", max_length=200)
    nome = models.CharField(verbose_name="Nome", max_length=200)
    telefone = models.CharField(verbose_name="Telefone", max_length=15)
    email = models.EmailField(verbose_name="Email", max_length=200)

    def __str__(self):
        return self.nome


class Discente(models.Model):

    PERIODO = [
        ('1', '1º'),
        ('2', '2º'),
        ('3', '3º'),
        ('4', '4º'),
        ('5', '5º'),
        ('6', '6º'),
        ('7', '7º'),
        ('8', '8º'),
        ('9', '9º'),
        ('10', '10º'),

    ]
    usuario = models.OneToOneField(User, on_delete=models.CASCADE, related_name="discente")
    imagem = models.ImageField(null=True, blank=True, default='padrao.png')
    matricula = models.CharField(verbose_name="MatDiscente", max_length=200)
    nome = models.CharField(verbose_name="Nome", max_length=200)
    periodo = models.CharField(verbose_name="Período", max_length=3)
    telefone = models.CharField(verbose_name="Telefone", max_length=15)
    email = models.EmailField(verbose_name="Email", max_length=200)

    def __str__(self):
        return self.nome

pacientes/forms.py
from django import forms
from django.forms import fields
from pacientes.models import Paciente, PacienteInfantil


class PacienteForm(forms.ModelForm):
    class Meta:
        model = Paciente
        exclude = ('num_prontuario',)

class PacienteInfantilForm(forms.ModelForm):
    class Meta:
        model = PacienteInfantil
        fields = "__all__"

pacientes/templates/pacientes/agenda.html
{% extends "pacientes/base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block agenda %}{% endblock agenda %}
{% block content %}
<div class="container">

    <div class="col-md-5">
        <h3>AGENDA</h3>



    </div>
</div>

{% endblock content %}

pacientes/templates/pacientes/paciente_delete_inf.html
{% extends "pacientes/base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
    <div class="col-md-6 mx-auto">
        <h3><b>Excluir Registro</b></h3>
        <p class="lead">Tem certeza que deseja excluir o registro do paciente</p>
        <h3><p><strong>{{object.nome}}</strong> ?</p></h3>
        <form method="post">{% csrf_token %}
            {{ form|crispy }}
            <div class="col-md-6 ml-auto">
                <a class="btn btn-secondary btn-sm" href= "{% url 'paciente_detalhes_inf' object.pk %}" >Cancelar</a>
                <input  class="btn btn-danger btn-sm"  type="submit" value="Excluir">
            </div>
        </form>
    </div>
</div>

{% endblock content %}

pacientes/templates/pacientes/paciente_detalhes_inf.html
{% extends "pacientes/base.html" %}
{% load static %}
{% load crispy_forms_tags %}
    {% block content %}
<div class="container">
    <div class="card shadow mb-4">
        <div class="card-body">
            <h4 class="mb-3 text-primary">
            <h1>{{ object.nome }}</h1>
            </h4>
            <form>
                <div class="form-row">
                    <div class="form-group col-md-4">
                        <label>Nome Social</label>
                        <input type="text" class="form-control" value="{{ object.nome_social}}" disabled>
                    </div>

                    <div class="form-group col-md-4">
                        <label>Data de nascimento</label>
                        <input type="text" class="form-control" value="{{ object.data_nascimento }}" disabled>
                    </div>

                    <div class="form-group col-md-4">
                        <label>Sexo Biologico</label>
                        <input type="text" class="form-control" value="{{ object.sexo_biologico }}" disabled>
                    </div>
                </div>

                <div class="form-row">
                    <div class="form-group col-md-4">
                        <label>RG</label>
                        <input type="text" class="form-control" value="{{ object.rg}}" disabled>
                    </div>

                    <div class="form-group col-md-4">
                        <label>CPF</label>
                        <input type="text" class="form-control" value="{{ object.cpf }}" disabled>
                    </div>

                    <div class="form-group col-md-4">
                        <label>Raça</label>
                        <input type="text" class="form-control" value="{{ object.raca}}" disabled>
                    </div>


                </div>
            </form>
            <form>
                <div class="form-row">
                    <div class="form-group col-md-4">
                        <label>Estado Civil</label>
                        <input type="text" class="form-control" value="{{ object.estado_civil }}" disabled>
                    </div>

                    <div class="form-group col-md-4">
                        <label>Grau de instrução</label>
                        <input type="text" class="form-control" value="{{ object.grau_instrucao }}" disabled>
                    </div>
                    <div class="form-group col-md-4">
                        <label>Endereço</label>
                        <input type="text" class="form-control" value="{{ object.endereco }}" disabled>
                    </div>
                </div>

                <div class="form-row">
                    <div class="form-group col-md-4">
                        <label>Cep</label>
                        <input type="text" class="form-control" value="{{ object.cep}}" disabled>
                    </div>
                    <div class="form-group col-md-4">
                        <label>Bairro</label>
                        <input type="text" class="form-control" value="{{ object.bairro }}" disabled>
                    </div>
                    <div class="form-group col-md-4">
                        <label>Cidade</label>
                        <input type="text" class="form-control" value="{{ object.cidade }}" disabled>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label>UF</label>
                        <input type="text" class="form-control" value="{{ object.uf }}" disabled>
                    </div>
                    <div class="form-group col-md-6">
                        <label>Telefone</label>
                        <input type="text" class="form-control" value="{{ object.telefone_celular }}" disabled>
                    </div>
                </div>
            </form>
            <div class="mr-1 text-right">
                <a href="#" class="btn btn-secondary text-white" type="button">
                    <span class="text">Voltar</span>
                </a>
                <a href="{% url 'paciente_delete_inf' object.pk %}" class="btn btn-danger text-white" type="button">
                    <span class="text">Excluir</span>
                </a>
            </div>
        </div>
    </div>
    </div>
    </div>
</div>
{% endblock content %}

pacientes/templates/pacientes/paciente_registrar2.html
{% extends "pacientes/base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-success" role="alert">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800"></h1>
    </div>
    <div class="card shadow mb-4">
        <div class="card-body">
            <h4 class="mb-3 text-primary">
                Formulário Para Registro de Novo Paciente
            </h4>
            <p class="mb-5 ml-1">
                <small>
                O asterisco (*) indica que o campo é obrigatório
                </small>
            </p>
        <form method="post" action="{% url 'paciente_registrar' %}">
            {% csrf_token %}
            <div class="form-row">
                <div class="form-group col-md-3">
                    <label>Nome </label>
                    <input type="text" class="form-control" value="{{ object.nome }}" name="nome">
                </div>
                <div class="form-group col-md-3">
                    <label>Nome Social</label>
                    <input type="text" class="form-control" value="{{ object.nome_social}}" name="nome_social">
                </div>

                <div class="form-group col-md-3">
                    <label>Data de nascimento</label>
                    <input type="Date" class="form-control" id="id_data" value="{{ object.data_nascimento }}" name="data_nascimento">
                </div>

                <div class="form-group col-md-3">
                    <label>Sexo Biologico</label>
                    <div class="">
                        <select name="sexo_biologico" class="select form-control" id="id_sexo_biologico">
                            <option value="">---------</option>
                            <option value="MASCULINO">Masculino</option>
                            <option value="FEMININO">Feminino</option>
                        </select>
                    </div>
                </div>
            </div>
                <div class="form-row">
                <div class="form-group col-md-4">
                    <label>RG</label>
                    <input type="text" class="form-control" value="{{ object.rg}}" name="rg">
                </div>
                <div class="form-group col-md-4">
                    <label>CPF</label>
                    <input type="text" class="form-control" id="id_cpf" value="{{ object.cpf }}" name="cpf">
                </div>
                <div class="form-group col-md-4">
                    <label>Raça</label>
                    <div class="">
                        <select name="raca" class="select form-control">
                            <option value="">---------</option>
                            <option value="BRANCO">Branco</option>
                            <option value="PARDO">Pardo</option>
                            <option value="INDIGENA">Indígena</option>
                            <option value="AMARELO">Amarelo</option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-4">
                    <label>Estado Civil</label>
                    <div class="">
                        <select name="estado_civil" class="select form-control">
                            <option value="">---------</option>
                            <option value="SOLTEIRO(A)">SOLTEIRO</option>
                            <option value="CASADO(A)">CASADO</option>
                            <option value="SEPARADO(A)">SEPARADO</option>
                            <option value="DIVORCIADO(A)">DIVORCIADO</option>
                            <option value="VIUVO(A)">VIUVO</option>
                        </select>
                    </div>
                </div>
                <div class="form-group col-md-4">
                    <label>Grau de Instrução</label>
                    <div class="">
                        <select name="grau_instrucao" class="select form-control">
                            <option value="">---------</option>
                            <option value="Analfabeto">Analfabeto</option>
                            <option value="Fundamental Incompleto">Fundamental Incompleto</option>
                            <option value="Fundamental Completo">Fundamental Completo</option>
                            <option value="Medio Incompleto">Médio Incompleto</option>
                            <option value="Médio Completo">Médio Completo</option>
                            <option value="Superior Incompleto">Superior Incompleto</option>
                            <option value="Superior Completo">Superior Completo</option>
                            <option value="Mestrado">Mestrado</option>
                            <option value="Doutorado">Doutorado</option>
                        </select>
                    </div>
                </div>
                  <div class="form-group col-md-4">
                    <label>Cep</label>
                    <input type="text" class="form-control" id="id_cep" value="{{ object.cep}}" name="cep">
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-4">
                    <label>Logradouro</label>
                    <input type="text" class="form-control" id="id_rua" value="{{ object.endereco }}" name="endereco">
                </div>
                <div class="form-group col-md-4">
                    <label>Bairro</label>
                    <input type="text" class="form-control" id="id_bairro" value="{{ object.bairro }}" name="bairro">
                </div>
                <div class="form-group col-md-4">
                    <label>Cidade</label>
                    <input type="text" class="form-control" id="id_cidade" value="{{ object.cidade }}" name="cidade">
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-4">
                    <label>UF</label>
                    <div class="">
                        <select name="uf" id="id_uf" class="select form-control">
                            <option value="">---------</option>
                            <option value="AC">Acre</option>
                            <option value="AM">Amazonas</option>
                            <option value="AL">Alagoas</option>
                            <option value="AP">Amapá</option>
                            <option value="BA">Bahia</option>
                            <option value="CE">Ceará</option>
                            <option value="DF">Distrito Federal</option>
                            <option value="ES">Espírito Santo</option>
                            <option value="GO">Goiás</option>
                            <option value="MA">Maranhão</option>
                            <option value="MG">Minas Gerais</option>
                            <option value="MS">Mato Grosso do Sul</option>
                            <option value="MT">Mato Grosso</option>
                            <option value="PA">Pará</option>
                            <option value="PB">Paraíba</option>
                            <option value="PE">Pernambuco</option>
                            <option value="PI">Piauí</option>
                            <option value="PR">Paraná</option>
                            <option value="RJ">Rio de Janeiro</option>
                            <option value="RN">Rio Grande do Norte</option>
                            <option value="RO">Rondônia</option>
                            <option value="SC">Santa Catarina</option>
                            <option value="SE">Sergipe</option>
                            <option value="SP">São Paulo</option>
                            <option value="TO">Tocantins</option>

                        </select>
                    </div>
                </div>
                <div class="form-group col-md-4">
                    <label>Telefone</label>
                    <input type="text" class="form-control" id="id_telefone_celular" value="{{ object.telefone_celular }}" name="telefone_celular">
                </div>
                <div class="form-group col-md-4">
                    <label>Prontuario</label>
                    <input type="text" class="form-control" value="{{ prontuario.num_prontuario}}" disabled>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-12">
                    <label>Informações Complementares</label>
                    <textarea type="textarea" cols="40" rows="10" class="textarea form-control" value="{{ object.informacoes_complementares }}" name="informacoes_complementares"></textarea>
                </div>
            </div>
                <div class="mr-1 text-right">
                    <button type="submit" class="btn btn-primary text-white ">Cadastrar</button>
                </div>
        </form>
        </div>
    </div>
</div>
{% endblock content%}
{% block scripts %}
<script type="text/javascript">

$(function(){
    function limpa_cpf() {
                // Limpa valores do formulário de cep.
                $("#id_cpf").val("");

            }
    //Executa a requisição quando o campo username perder o foco
    $('#id_cpf').blur(function()
    {
        var cpf = $('#id_cpf').val().replace(/[^0-9]/g, '').toString();

        if( cpf.length == 11 )
        {
            var v = [];

            //Calcula o primeiro dígito de verificação.
            v[0] = 1 * cpf[0] + 2 * cpf[1] + 3 * cpf[2];
            v[0] += 4 * cpf[3] + 5 * cpf[4] + 6 * cpf[5];
            v[0] += 7 * cpf[6] + 8 * cpf[7] + 9 * cpf[8];
            v[0] = v[0] % 11;
            v[0] = v[0] % 10;

            //Calcula o segundo dígito de verificação.
            v[1] = 1 * cpf[1] + 2 * cpf[2] + 3 * cpf[3];
            v[1] += 4 * cpf[4] + 5 * cpf[5] + 6 * cpf[6];
            v[1] += 7 * cpf[7] + 8 * cpf[8] + 9 * v[0];
            v[1] = v[1] % 11;
            v[1] = v[1] % 10;

            //Retorna Verdadeiro se os dígitos de verificação são os esperados.
            if ( (v[0] != cpf[9]) || (v[1] != cpf[10]) )
            {
                limpa_cpf();
                alert('CPF inválido: ' + cpf);
            }
        }
        else
        {
            limpa_cpf();
            alert('CPF inválido:' + cpf);
        }
    });
});
</script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"
            integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
            crossorigin="anonymous"></script>

    <!-- Adicionando Javascript -->
<script>
    $(document).ready(function() {

        function limpa_formulário_cep() {
            // Limpa valores do formulário de cep.
            $("#id_rua").val("");
            $("#id_bairro").val("");
            $("#id_cidade").val("");
            $("#id_uf").val("");
            $("#ibge").val("");
        }

        //Quando o campo cep perde o foco.
        $("#id_cep").blur(function() {

            //Nova variável "cep" somente com dígitos.
            var cep = $(this).val().replace(/\D/g, '');

            //Verifica se campo cep possui valor informado.
            if (cep != "") {

                //Expressão regular para validar o CEP.
                var validacep = /^[0-9]{8}$/;

                //Valida o formato do CEP.
                if(validacep.test(cep)) {

                    //Preenche os campos com "..." enquanto consulta webservice.
                    $("#id_rua").val("...");
                    $("#id_bairro").val("...");
                    $("#id_cidade").val("...");
                    $("#id_uf").val("...");
                    $("#ibge").val("...");

                    //Consulta o webservice viacep.com.br/
                    $.getJSON("https://viacep.com.br/ws/"+ cep +"/json/?callback=?", function(dados) {

                        if (!("erro" in dados)) {
                            //Atualiza os campos com os valores da consulta.
                            $("#id_rua").val(dados.logradouro);
                            $("#id_bairro").val(dados.bairro);
                            $("#id_cidade").val(dados.localidade);
                            $("#id_uf").val(dados.uf);
                            $("#ibge").val(dados.ibge);
                        } //end if.
                        else {
                            //CEP pesquisado não foi encontrado.
                            limpa_formulário_cep();
                            alert("CEP não encontrado.");
                        }
                    });
                } //end if.
                else {
                    //cep é inválido.
                    limpa_formulário_cep();
                    alert("Formato de CEP inválido.");
                }
            } //end if.
            else {
                //cep sem valor, limpa formulário.
                limpa_formulário_cep();
            }
        });
    });

    </script>
<script src="{% static 'js/jquery.mask.min.js' %}"></script>
<script>
    $(document).ready(function(){

        $("#id_dat").mask("00/00/0000");
        $('#id_cep').mask('00000-000');
        $('#id_cpf').mask('000.000.000-00');
        $('#id_telefone').mask('(00) 00000-0000');
        });
</script>
<script src="{% static 'js/valida_cpf.js' %}"></script>

{% endblock scripts %}